"""add folder relationships

Revision ID: 83935196be28
Revises: 345dc0ee3ab2
Create Date: 2026-05-11 23:51:04.210619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83935196be28'
down_revision: Union[str, Sequence[str], None] = '345dc0ee3ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'folder_id')
    # ### end Alembic commands ###
